### ISSUE TITLE
angler js bug

### ISSUE THREAD

**Issue by wingchen** [qq830214a/bobigreencard#7]
@larrychen-ca 
angler js bug

Do you mind taking a look?

I got that when loading the page on chrome locally.

```
Error: Failed to construct 'Worker': Script at 'file:///opt/bobigreencard/js/papaparse.min.js?papaworker' cannot be accessed from origin 'null'.
    at Error (native)
    at f (file:///opt/bobigreencard/js/papaparse.min.js:6:11265)
    at Object.t [as parse] (file:///opt/bobigreencard/js/papaparse.min.js:6:91)
    at HackathonController.parseCSV (file:///opt/bobigreencard/js/hackathon.js:235:10)
    at new HackathonController (file:///opt/bobigreencard/js/hackathon.js:169:10)
    at Object.e [as invoke] (file:///opt/bobigreencard/js/angular.min.js:39:96)
    at $get.Q.instance (file:///opt/bobigreencard/js/angular.min.js:80:151)
    at K (file:///opt/bobigreencard/js/angular.min.js:61:140)
    at g (file:///opt/bobigreencard/js/angular.min.js:54:326)
    at g (file:///opt/bobigreencard/js/angular.min.js:54:349)
```

**Comment by larrychen-ca** [comment]
@wingchen Interesting, I didn't encounter that. What's your browser version and how were you viewing the site?

**Comment by larrychen-ca** [comment]
@wingchen actually please refer to this discussion http://stackoverflow.com/questions/21408510/chrome-cant-load-web-worker on why you saw the error. It's a security issue and you should be viewing the website through a proxy/web server instead of loading the files locally.

I was developing using WebStorm and using its internal web server that's why I didn't see the error. Try to set the value for the 'worker' property to 'false' on line 229 in 'hackathon.js' and see if that error disappear.

**Comment by wingchen** [comment]
My bad. We cannot load it directly from local file already. It requires to be run with a http server.
I did this, and it worked:
1. cd <bobigreencard folder> 
2. python -m SimpleHTTPServer 8080
3. Go open chrome to address 0.0.0.0:8080

It worded there. I am going to put this info into the readme then.
